# The configuration file of quantum random number generation.

# the count of numbers you needed
bit_len = 10

# the physical processor
backend = 'local_baidu_sim2'
# backend = 'cloud_baidu_sim2_water'
# backend = 'cloud_baidu_sim2_earth'
# backend = 'cloud_baidu_sim2_thunder'
# backend = 'cloud_baidu_sim2_heaven'
# backend = 'cloud_baidu_sim2_wind'
# backend = 'cloud_baidu_sim2_lake'
# backend = 'cloud_aer_at_bd'
# backend = 'cloud_baidu_qpu_qian'
# backend = 'cloud_iopcas'
# backend = 'cloud_ionapm'
# backend = 'service_ubqc'

# user's token for cloud service
token = ''

# whether to use extractor for post-process, please use lowercase here
extract = false

# security parameters
security = 1e-8

# the min-entropy of hardware 1 and hardware 2, range from (0,1)
min_entr_1 = 0.9 
min_entr_2 = 0.9

# the save path of log file
log_path = './qrng.log'
