# The config for credit risk analysis model
# number of assets.
num_assets = 4
# basic default probabilities.
base_default_prob = [0.15, 0.25, 0.39, 0.58]
# sensitivity.
sensitivity = [0.37, 0.21, 0.32, 0.02]
# loss given default.
lgd = [5, 1, 3, 4]
# confidence level.
confidence_level = 0.99
# degree of simulation. Higher the degree, preciser the simulation.
degree_of_simulation = 4
