# The config for testing the QNNQD model.
# The task of this config. Available values: 'train' | 'test'.
task = 'test'

# The path of the input image.
image_path = 'SurfaceCrack/test_data/'

# The number of the data in the test dataset.
# The value defaults to -1 which means using all data.
num_samples = -1

# The path of the trained model, which will be loaded.
model_path = 'qnnqd.pdparams'

# The number of qubits of the quantum circuit in each layer.
num_qubits = [4,4]

# The depth of the quantum circuit in each layer.
num_depths = [2,2]

# The observables of the quantum circuit in each layer.
observables = [['Z0','Z1','Z2','Z3'], ['Z0','Z1','Z2','Z3']]
